title: Deep Kapadia 
email: deep@thisdomain
description: >- # this means to ignore newlines until "baseurl:"
    I work at The New York Times. I solve problems with help of people and code.
    I am currenty managing a team of SRE's and automation engineers. 
    When I am not working, I am a struggling dad and husband. 
    I grew up in Delhi and Mumbai, and now live in Hoboken, NJ.
baseurl: "/" 
url: "https://deepkapadia.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: durple
github_username:  durple

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
