title: Deep Kapadia 
description: >- # this means to ignore newlines until "baseurl:"
       Dad, husband, software engineer, sports enthusiast 
baseurl: "/" 
url: "https://deepkapadia.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: durple
github_username:  durple

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
plugins:
  - jekyll-feed
show_excerpts: true
